### ISSUE TITLE
Expect type to equal type hanging MS & Resharper test runners in DotNetCore 2.0

### ISSUE THREAD

**Issue by brendon1982** [fluffynuts/NExpect#12]
With:
DotNetCore 2.0
NUnit 3.9.0
Visual Studio 2017 15.5.1

The following expectation will hang both MS and Resharper test runners (on my machine ;D):

Expect(new Object().GetType()).To.Equal(typeof(Object));

**Comment by fluffynuts** [comment]
This issue is specific to dotnet core: turns out types are enumerable on dnc, so the Stringifier attempts to create a string representation of it and linked properties -- ending up trying to stringify the entire app domain. I've added a type-specific Stringify special case (go, go strategies!) which uses the venerable PeanutButter {Type}.PrettyName() extension to get a fully-qualified name for the type.

Issue is resolved in package 1.0.97.
