### ISSUE TITLE
Null assertion not being recognized by IDE

### ISSUE THREAD

**Issue by sduduzog** [fluffynuts/NExpect#17]
This is not a trains mash but it would be nice to have that 'Possible NullReferenceException' underline go away when I've expected it not to be. See screenshots
![image](https://user-images.githubusercontent.com/48126337/76065836-0f51b400-5f95-11ea-8900-33eacff12893.png)

![image](https://user-images.githubusercontent.com/48126337/76066025-65bef280-5f95-11ea-9c60-36aac1f8399a.png)

**Comment by fluffynuts** [comment]
I've brought this up with JetBrains before. Apparently there are ways to annotate code to help with the warnings (these warnings are from R#). However, those methods are only capable of doing so at the original call site -- in other words, there's (apparently) no way for those annotations to "recognise" that `Expect(campaignTemplateResult)` will chain on to `Not.To.Be.Null()`; this is why you don't get the warning if using NUnit's `Assert.That(foo, Is.Not.Null)` or `Assert.IsNotNull(foo)` -- because, in both cases, there's a single function call which can be correctly decorated to help the R# engine to figure out that, by the next line, `foo` won't be null.

It may be time for me to see if there's not a hacky method to bypass this, but I'm not very optimistic that I'll find one, based on the conversation I've already had with JetBrains, sorry ):
