### ISSUE TITLE
publish GitHub releases 

### ISSUE THREAD

**Issue by viceice** [fluffynuts/NExpect#32]
it would be nice to have GitHub releases with changelog. that way renovatebot can show recharged in upgrade PR body.

**Comment by viceice** [comment]
sample renovate PR
- https://github.com/visualon/featureide.net/pull/30

**Comment by fluffynuts** [comment]
NExpect does _a lot_ of minor, incremental releases. Currently, tag & publish is automated (one npm command) - I wouldn't be adverse to, eg, a GitHub workflow like https://github.com/marketplace/actions/create-tag-release - however that one requires manually filling in the changelog. I'm open for ideas - a workflow should:
1. be triggered on a tag being pushed
2. create a release with the same name as the tag
3. collate all git commit messages between this tag and the last one, stripping out any massages starting with `:bookmark:` (the tag commit) and probably stripping out any leading gitmoji? I'm not sure about the last bit as I'm not sure what difference that would make to renovatebot - perhaps they can be left in. 

At any rate, the very last thing I want to do is add more friction to a release, most especially because I may do 5 or 10 releases in a day as I'm extending NExpect (or a periphery Matchers package) to support the work I'm currently doing. If there's an automated solution, I'm interested - and I'm asking for help to find one, since a cursory web search revealed the one above and it's incomplete for my requirements.

**Comment by fluffynuts** [comment]
btw, whilst minor bumps have (perhaps) interesting commentary about added features and the odd fixed bug, the reason for the major version bump was because I dropped support for `net452` as (a) it's about time and (b) it was making life difficult :D

**Comment by viceice** [comment]
let me try to compose some GitHub workflow for you.

**Comment by fluffynuts** [comment]
when you crack it, please make it easily available for others - I'm sure this is not a unique problem (:

**Comment by viceice** [comment]
> when you crack it, please make it easily available for others - I'm sure this is not a unique problem (:

sure, I'll try to compose the solution from existing tools / actions. i already have some ideas.

**Comment by viceice** [comment]
@fluffynuts got something working 🎉 let me know if you like that. it would be enough for me to see whats changed
